Addition of Name Spacing to PAA Ext
InteractiveAdvertisingBureau/openrtb pull request #175
Opened 2024-06-21 15:20 UTC by hillslatt

**New**

- Section: Non-ORTB Signaling 
- Object: InterestGroupAuctionBuyerSignals
- Attributes: 
- - InterestGroupAuctionSupport.pbsmap
- - InterestGroupAuctionBuyer.pbsmap
- Additional Implementation Guidance for name spacing

2024-06-26 22:15 UTC, patmmccann commented on extensions/community_extensions/Protected Audience Support.md
> +	0 = no; igb.pbs value is passthrough (DEFAULT)<br>
We should just choose the best place, not provide two different places to put the thing. We should only do 1, yes, below

2024-06-28 14:00 UTC, rdgordon-index reviewed
whitespace changes only

2024-06-28 14:00 UTC, rdgordon-index commented on extensions/community_extensions/Protected Audience Support.md
> +"https://dsp.example": ... // BidResponse.ext.igi[].igb[].pbs
```suggestion
   "https://dsp.example": ... // BidResponse.ext.igi[].igb[].pbs
```

2024-06-28 14:00 UTC, rdgordon-index commented on extensions/community_extensions/Protected Audience Support.md
> +"https://dsp.example": {
```suggestion
   "https://dsp.example": {
```

2024-08-02 12:32 UTC, patmmccann commented on extensions/community_extensions/Protected Audience Support.md
> +If the buyer opts into perBuyerSignals namespacing by returning pbsmap = 1, then the seller/SSP provides perBuyerSignalls as:
we should delete this and always namespace

2024-08-02 12:32 UTC, patmmccann commented on extensions/community_extensions/Protected Audience Support.md
> +"https://dsp.example": ... // BidResponse.ext.igi[].igb[].pbs
we should delete this part and always name space

2024-08-16 15:17 UTC, dmdabbs requested changes
>BidResponse.ext.igi: This extension to "Object: Bid" 

This is an extension to BidResponse not object Bid. One can no bid and still pass intent to participate in a (potential) PA auciton.

2024-08-16 15:56 UTC, merged